[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "npx drizzle-kit push"
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
